"""Add SafetyAssessments table

Revision ID: 0d806b7f685b
Revises: 7a61cc1c93c4
Create Date: 2026-07-19 16:13:19.457727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d806b7f685b'
down_revision = '7a61cc1c93c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('safety_data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_assessments_destination'), ['destination'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safety_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_assessments_destination'))

    op.drop_table('safety_assessments')
    # ### end Alembic commands ###
