"""Add POIs table

Revision ID: 461a895814b1
Revises: d09b87238674
Create Date: 2026-07-19 16:03:06.934785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461a895814b1'
down_revision = 'd09b87238674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('poi_data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pois_destination'), ['destination'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pois', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pois_destination'))

    op.drop_table('pois')
    # ### end Alembic commands ###
